#:schema node_modules/wrangler/config-schema.json
name = "authsmith"
main = "./apps/www/server.ts"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

kv_namespaces = [{ binding = "cache", id = "cache" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./apps/www/build/client"

[build]
command = "pnpm run build:www"